### ISSUE TITLE
repomd.xml missing in packagecloud.io

### ISSUE THREAD

**Issue by nodanero** [lest/prometheus-rpm#53]
Hi,

It seems that the metadata of the repository is missing

root@localhost root]# reposync -l --repoid=prometheus --download_path=/var/repos/prometheus-centos7
Loaded plugins: product-id, subscription-manager
rhel-7-server-rpms                                                                                                                                                        | 3.5 kB  00:00:00
Error setting up repositories: failure: repodata/repomd.xml from prometheus: [Errno 256] No more mirrors to try.
https://packagecloud.io/prometheus-rpm/release/el/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 302 - Found

Can you generate it?

Best Regards,

Joaquin

**Comment by zoonage** [comment]
@nodanero I think that Package Cloud were experiencing an issue, the metadata is back now.

**Comment by zoonage** [comment]
@nodanero  is this still an issue?

**Comment by zoonage** [comment]
@nodanero or @ak-uk  did you install it using the script from package cloud or from the `README.md`? Could you please put the contents of `/etc/yum.repos.d/prometheus-rpm_release.repo` or `/etc/yum.repos.d/prometheus.repo` (depending on the installation method) into this ticket so I can try and troubleshoot with the same setup as you?

**Comment by ak-uk** [comment]
[prometheus]
name=prometheus
baseurl=https://packagecloud.io/prometheus-rpm/release/el/7/x86_64
repo_gpgcheck=1
enabled=1
gpgkey=https://packagecloud.io/prometheus-rpm/release/gpgkey
gpgcheck=1

**Comment by zoonage** [comment]
Sorry to ask again - @nodanero or @ak-uk did you install it using the script from package cloud or from the `README.md`?

**Comment by lest** [comment]
I did some testing. Initially, `reposync` failed with:

```
[root@40efaceddcc0 /]# reposync -l --repoid=prometheus --download_path=/var/repos/prometheus-centos7                                                           
Loaded plugins: fastestmirror, ovl                                                                                                                             
Loading mirror speeds from cached hostfile                                                                                                                     
 * base: mirror.mirohost.net                                                                                                                                   
 * extras: mirror.mirohost.net                                                                                                                                 
 * updates: mirror.mirohost.net                                                                                                                                
prometheus/signature                                                                                                                     |  833 B  00:00:00     
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
prometheus/signature                                                                                                                     |  833 B  00:00:00    
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
prometheus/signature                                                                                                                     |  833 B  00:00:00    
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
prometheus/signature                                                                                                                     |  833 B  00:00:00    
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
prometheus/signature                                                                                                                     |  833 B  00:00:00    
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
prometheus/signature                                                                                                                     |  833 B  00:00:00    
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
prometheus/signature                                                                                                                     |  833 B  00:00:00
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
prometheus/signature                                                                                                                     |  833 B  00:00:00
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
prometheus/signature                                                                                                                     |  833 B  00:00:00
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
prometheus/signature                                                                                                                     |  833 B  00:00:00
prometheus/signature                                                                                                                     | 1.0 kB  00:00:00 !!!
Traceback (most recent call last):
  File "/usr/bin/reposync", line 373, in <module>
    main()
  File "/usr/bin/reposync", line 185, in main
    my.doRepoSetup()
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 681, in doRepoSetup
    return self._getRepos(thisrepo, True)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 721, in _getRepos
    self._repos.doSetup(thisrepo)
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 157, in doSetup
    self.retrieveAllMD()
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 88, in retrieveAllMD
    dl = repo._async and repo._commonLoadRepoXML(repo)
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1482, in _commonLoadRepoXML
    result = self._getFileRepoXML(local, text)
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1259, in _getFileRepoXML
    size=102400) # setting max size as 100K
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1042, in _getFile
    raise e
yum.Errors.NoMoreMirrorsRepoError: failure: repodata/repomd.xml from prometheus: [Errno 256] No more mirrors to try.
https://packagecloud.io/prometheus-rpm/release/el/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for prometheus
```

However, it worked after either switching `repo_gpgcheck` to `0` or installing one of packages with `yum install` and accepting GPG keys when prompted.
